version: '3.0'

services:
    sre_terraform:
      build:
        context: .
        args:
          - TERRAFORM_VERSION=${TERRAFORM_VERSION}
      image: sre_terraform
      environment:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_DEFAULT_REGION=us-east-1
      volumes:
        - ./terraform:/app/terraform
        - ./ansible:/app/ansible
        - ./ssh/:/app/ssh
      working_dir: /app